[status_bar]
fg = "Black"
bg = "Gray"

[command_line]
fg = "Black"
bg = "White"

[input_mode]
fg = "Black"
bg = "White"

[user_feedback]
fg = "Black"
bg = "White"

[canvas.default_style]
fg = "Black"
bg = "White"
