[status_bar]
fg = "#b1b1b1"
bg = "#393a31"

[canvas.default_style]
fg = "#ffffff"
bg = "#272822"

[canvas.standard_colors]
black = "#1a1a1a"
red = "#f4005f"
green = "#98e024"
yellow = "#fa8419"
blue = "#9d65ff"
magenta = "#f332fa"
cyan = "#58d1eb"
white = "#c4c5b5"
bright_black = "#625e4c"
bright_red = "#f4005f"
bright_green = "#98e024"
bright_yellow = "#e0d561"
bright_blue = "#9d65ff"
bright_magenta = "#f332fa"
bright_cyan = "#58d1eb"
bright_white = "#f6f6ef"

