[canvas.default_style]
fg = "White"
bg = "#300a24"

# Ubuntu colors as described at https://en.wikipedia.org/wiki/ANSI_escape_code
[canvas.standard_colors]
black = "#010101"
red = "#de382b"
green = "#39b54a"
yellow = "#ffc706"
blue = "#006fb8"
magenta = "#762671"
cyan = "#2cb5e9"
white = "#cccccc"
bright_black = "#808080"
bright_red = "#ff0000"
bright_green = "#00ff00"
bright_yellow = "#ffff00"
bright_blue = "#0000ff"
bright_magenta = "#ff00ff"
bright_cyan = "#00ffff"
bright_white = "#ffffff"
