[canvas.default_style]
fg = "Gray"
bg = "Black"

# VGA colors as described at https://en.wikipedia.org/wiki/ANSI_escape_code
[canvas.standard_colors]
black = "#000000"
red = "#aa0000"
green = "#00aa00"
yellow = "#aa5500"
blue = "#0000aa"
magenta = "#aa00aa"
cyan = "#00aaaa"
white = "#aaaaaa"
bright_black = "#555555"
bright_red = "#ff5555"
bright_green = "#55ff55"
bright_yellow = "#ffff55"
bright_blue = "#5555ff"
bright_magenta = "#ff55ff"
bright_cyan = "#55ffff"
bright_white = "#ffffff"
